from __future__ import annotations

from mama.platforms.registry import PLATFORMS


# The CMake condition that identifies each platform, in the order mama.cmake tests them. The order is
# the registry's, and it matters: android is also UNIX and iOS is also APPLE, so the specific guard
# must come first. A consumer's CMakeLists cannot detect a platform missing from here.
_GUARDS = {
    'android': 'ANDROID OR ANDROID_NDK',
    'windows': 'WIN32',
    'ios':     'APPLE AND IOS_PLATFORM',
    'macos':   'APPLE',
    'raspi':   'RASPI',
    'oclea':   'OCLEA',
    'xilinx':  'XILINX',
    'imx8mp':  'IMX8MP',
    'mips':    'MIPS',
    'linux':   'UNIX',
}

# Variables a consumer's CMakeLists has always been able to test, beyond the platform's own define.
_EXTRA_VARS = {'ios': ('IOS',), 'macos': ('MACOS',), 'linux': ('LINUX',)}

# The MAMA_CMAKE_ARCH pattern and the variable each arch sets. mama.cmake tests them in THIS order, so
# x64 wins before x86 (which also matches x86_64) and mips64el before mips. Each pattern is a union of
# what CMAKE_GENERATOR_PLATFORM, ANDROID_ARCH and CMAKE_SYSTEM_PROCESSOR report for that arch.
_ARCH_MATCH = (
    ('x64',      'MAMA_ARCH_X64',   '(amd64)|(AMD64)|(IA64)|(x64)|(X64)|(x86_64)|(X86_64)'),
    ('x86',      'MAMA_ARCH_X86',   '(X86)|(x86)|(i386)|(i686)'),
    ('arm64',    'MAMA_ARCH_ARM64', '(aarch64)|(AARCH64)|(arm64)|(ARM64)'),
    ('arm',      'MAMA_ARCH_ARM32', '(armv7)|(ARMV7)|(arm)|(ARM)'),
    ('mips64el', 'MAMA_ARCH_MIPS',  '(mips64el)|(MIPS64EL)'),
    ('mips64',   'MAMA_ARCH_MIPS',  '(mips64)|(MIPS64)'),
    ('mipsel',   'MAMA_ARCH_MIPS',  '(mipsel)|(MIPSEL)'),
    ('mips',     'MAMA_ARCH_MIPS',  '(mips)|(MIPS)'),
)


def _platform_header(platform) -> str:
    """The lines every arch of this platform shares: the variables a consumer can test."""
    lines = [f'set({var} TRUE)' for var in _EXTRA_VARS.get(platform.name, ())]
    for define, value in platform.compile_defines.items():
        lines += [f'set({define} TRUE)', f'add_compile_definitions({define}={value})']
    return ''.join(f'    {line}\n' for line in lines)


def _arch_branches(platform, build_dir_defines) -> str:
    """The per-arch body: set the arch variable and point MAMA_BUILD at that arch's build dir.

    A platform with one arch needs no branch at all. With several, an unmatched arch is a FATAL_ERROR:
    picking a build dir on a guess silently links the wrong architecture's libraries."""
    arches = [a for a in _ARCH_MATCH if a[0] in platform.supported_arches]
    if len(arches) == 1:
        arch, var, _ = arches[0]
        return f'    set({var} TRUE)\n    {build_dir_defines(platform.build_dirs.get(arch, platform.name))}\n'

    body = ''
    for i, (arch, var, pattern) in enumerate(arches):
        test = 'if' if i == 0 else 'elseif'
        body += f'    {test}(MAMA_CMAKE_ARCH MATCHES "{pattern}")\n'
        body += f'        set({var} TRUE)\n'
        body += f'        {build_dir_defines(platform.build_dirs.get(arch, platform.name))}\n'
    body += '    else()\n'
    body += f'        message(FATAL_ERROR "MAMA: Unrecognized {platform.name} architecture' \
            ' \'${MAMA_CMAKE_ARCH}\'")\n'
    body += '    endif()\n'
    return body


def platform_chain(build_dir_defines) -> str:
    """The whole if/elseif chain over every platform mama supports, generated from the registry.

    `build_dir_defines(build_dir)` returns the MAMA_BUILD lines for one build dir. Generated, so the
    chain and BuildConfig can no longer drift apart: they read the same build_dirs table."""
    chain = ''
    for i, platform in enumerate(PLATFORMS):
        test = 'if' if i == 0 else 'elseif'
        chain += f'{test}({_GUARDS[platform.name]})\n'
        chain += _platform_header(platform)
        chain += _arch_branches(platform, build_dir_defines)
    chain += 'else()\n'
    chain += '    message(FATAL_ERROR "mama build: Unsupported Platform! \'${MAMA_CMAKE_ARCH}\'")\n'
    chain += 'endif()\n'
    return chain


def mama_cmake_text(build_dir_defines) -> str:
    """The `mysource/mama.cmake` proxy a consumer's CMakeLists includes. It detects the platform and
    the arch the way cmake sees them, then includes that build dir's mama-dependencies.cmake."""
    return f'''# This file is auto-generated by mama build. Do not modify by hand!
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set(CLANG TRUE)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set(GCC TRUE)
endif()

if(CMAKE_GENERATOR_PLATFORM)
    set(MAMA_CMAKE_ARCH ${{CMAKE_GENERATOR_PLATFORM}})
elseif(ANDROID OR ANDROID_NDK)
    set(MAMA_CMAKE_ARCH ${{ANDROID_ARCH}})
elseif(CMAKE_SYSTEM_PROCESSOR)
    set(MAMA_CMAKE_ARCH ${{CMAKE_SYSTEM_PROCESSOR}})
else()
    message(FATAL_ERROR "MAMA: Missing CMake target architecture!")
endif()

# Initializes the INCLUDE and LIBS, they will overwritten in mama-dependencies.cmake
set(MAMA_INCLUDE "")
set(MAMA_LIBS "")

# Set MAMA_INCLUDES and MAMA_LIBS for each platform
{platform_chain(build_dir_defines)}
# Overrides linkage on MSVC to non-debug run-time library (TODO: make this configurable)
if(MSVC)
    add_definitions(-D_ITERATOR_DEBUG_LEVEL=0)
    foreach(MODE "_DEBUG" "_MINSIZEREL" "_RELEASE" "_RELWITHDEBINFO")
        string(REPLACE "/MDd" "/MD" TMP "${{CMAKE_C_FLAGS${{MODE}}}}")
        set(CMAKE_C_FLAGS${{MODE}} "${{TMP}}" CACHE STRING "" FORCE)
        string(REPLACE "/MDd" "/MD" TMP "${{CMAKE_CXX_FLAGS${{MODE}}}}")
        set(CMAKE_CXX_FLAGS${{MODE}} "${{TMP}}" CACHE STRING "" FORCE)
    endforeach(MODE)
endif()
'''
