"""Pins that the working-tree check ignores what mama generated, and still catches what a developer left.

mama writes `mama.cmake` into every dependency source dir. Counting it reported every clean dependency
as dirty, which cost each one a `git ls-files` it did not need.
"""
import os

from mama.utils import git_status as util


def _fingerprint(source_repo) -> str:
    util.forget_git_dir_fingerprint(source_repo)
    return util.git_dir_fingerprint(source_repo)


def _write(source_repo, name, text='x\n'):
    open(os.path.join(source_repo, name), 'w').write(text)


def test_the_proxy_mama_generated_leaves_the_tree_clean(source_repo):
    _write(source_repo, 'mama.cmake', '# generated by mamabuild\n')
    assert _fingerprint(source_repo) == ''


def test_a_file_the_developer_left_still_reports_dirty(source_repo):
    _write(source_repo, 'scratch.h', '#pragma once\n')
    assert _fingerprint(source_repo) != ''


def test_the_developer_file_still_wins_beside_the_generated_one(source_repo):
    _write(source_repo, 'mama.cmake', '# generated by mamabuild\n')
    _write(source_repo, 'scratch.h', '#pragma once\n')
    assert _fingerprint(source_repo) != ''


def test_an_edit_to_a_tracked_file_still_reports_dirty(source_repo):
    _write(source_repo, 'mama.cmake', '# generated by mamabuild\n')
    _write(source_repo, 'lib.cpp', 'int f(){return 2;}\n')
    assert _fingerprint(source_repo) != ''


def test_the_generated_file_costs_no_ls_files_call(source_repo):
    # the whole point: a clean dependency must not pay for a second git process
    _write(source_repo, 'mama.cmake', '# generated by mamabuild\n')
    util.forget_git_dir_fingerprint(source_repo)
    seen = []
    original = util._git_output
    util._git_output = lambda args, cwd: seen.append(args[0]) or original(args, cwd)
    try: util.git_dir_fingerprint(source_repo)
    finally: util._git_output = original
    assert seen == ['status']
